# Generated by Django 2.2.7 on 2019-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAPanel', '0002_auto_20191221_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('user_id', models.IntegerField()),
                ('upload_time', models.DateTimeField()),
                ('total_record', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bot_uploaded_files',
            },
        ),
        migrations.DeleteModel(
            name='Filedata',
        ),
    ]
