# Generated by Django 3.0.2 on 2020-01-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAPanel', '0003_auto_20191221_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotErrorLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('exception_class', models.CharField(blank=True, max_length=255, null=True)),
                ('txtappformno', models.CharField(blank=True, db_column='txtAppFormNo', max_length=100, null=True)),
                ('exception_dtl', models.CharField(blank=True, max_length=5000, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
            ],
            options={
                'db_table': 'bot_error_logs',
            },
        ),
    ]
