# Generated by Django 3.0 on 2019-12-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField()),
                ('app_no', models.CharField(max_length=50)),
                ('aps_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'upload_file_data',
            },
        ),
    ]
